### ISSUE TITLE
Embedded Flash Pro 6

### ISSUE THREAD

**Issue by kowalski100** [polarfire-soc/icicle-kit-reference-design#10]
Does the onboard Embedded Flash pro has **DEBUG** support on Icicle Production Kit or its only used as programmer?

Do I need external FlashPro-6 for debugging or onboard embedded FlashPro-6 does the job!

- Ijaz

**Comment by nitindeshpande** [comment]
@kowalski100
Embedded Flashpro supports Debug.

**Comment by kowalski100** [comment]
Thank you @nitindeshpande.
