### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by kowalski100** [polarfire-soc/icicle-kit-reference-design#12]
Hi,

Do we have any license information available with reference design images/source here?

**Comment by hughbreslin** [comment]
Hey @kowalski100 no we don't, it can be added in in a future release :) 

The Icicle Kit has an MPFS250T-FCVG484E part on it which is supported by the free Sliver License. Full info on license types and supported parts can be found [here](https://www.microchip.com/en-us/products/fpgas-and-plds/fpga-and-soc-design-tools/fpga/licensing)

**Comment by hughbreslin** [comment]
A license file was added with the latest release as well as the information on libero licensing, closing this.
